version: '3'
services:
  database_api_mobilidade:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: api_mobilidade
      POSTGRES_USER: apimobilidade
      POSTGRES_PASSWORD: passwd
    volumes:
      - "./database:/var/lib/postgresql/data"
    ports:
      - "6432:5432"

  java_api_mobilidade:
    environment:
      PATH: /opt/java/maven/apache-maven-3.6.3/bin:$PATH
      JAVA_HOME: /opt/java/jdk/jdk-13.0.2
    build:
      context: .
      dockerfile: ./java/Dockerfile
    volumes:
      - "../:/home/app"
    ports:
      - "8080:8080"
    depends_on: 
      - database_api_mobilidade
